@hostname = localhost
@port = 8080
@baseUrl = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}

POST http://{{baseUrl}}/test//dataselect HTTP/1.1
Content-Type: {{contentType}}

{
        "ybbm":"10001",             //医保编号
        "babm":"10001",             //病案号
        "yljgmc":"海淀医院",        //定点医疗机构名称
        "yljgdm":"123123345345",   //医疗机构代码
        "ybjsdj":"1",              //医保结算等级
        "sbsj":"20200515",         //申报时间
        "tbbm":"海淀医院",          //填报部门
        "tbr":"李四",              //填报人
        "pageNo":"",
        "pageSize":""
}

